framework:
    assets:
        packages:
            UniteCMSCoreBundle:
                json_manifest_path: "%kernel.project_dir%/public/bundles/unitecmscore/manifest.json"
                base_path: '/bundles/unitecmscore'
            UniteCMSCollectionFieldBundle:
                json_manifest_path: "%kernel.project_dir%/public/bundles/unitecmscollectionfield/manifest.json"
                base_path: '/bundles/unitecmscollectionfield'
            UniteCMSStorageBundle:
                json_manifest_path: "%kernel.project_dir%/public/bundles/unitecmsstorage/manifest.json"
                base_path: '/bundles/unitecmsstorage'
            UniteCMSWysiwygFieldBundle:
                json_manifest_path: "%kernel.project_dir%/public/bundles/unitecmswysiwygfield/manifest.json"
                base_path: '/bundles/unitecmswysiwygfield'
