framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    # uncomment this entire section to enable sessions
    session:
        handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    validation: { enable_annotations: true }

    form: ~
    templating:
        engines: ['twig']

    assets:
        json_manifest_path: "%kernel.project_dir%/public/bundles/unitedcmscore/manifest.json"
        packages:
            field:
                json_manifest_path: "%kernel.project_dir%/public/bundles/unitedcmscollectionfield/manifest.json"