knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: false
    template:
        pagination: 'UniteCMSCoreBundle:Pagination:sliding.html.twig'
        sortable: 'UniteCMSCoreBundle:Pagination:sortable_link.html.twig'
