# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        unite_core_user:
            entity:
                class: UniteCMSCoreBundle:User
                property: email

        unite_core_api_key:
            id: unite.cms.api_key_provider

    encoders:
        UniteCMS\CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # Disables authentication for assets and the profiler, adapt it according to your needs.
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Stateless api fire. Authentication is done via api token.
        # If Authentication-Fallback header is present, this firewall gets skipped and the main firewall will be used.
        api:
            anonymous: false
            provider: unite_core_api_key
            request_matcher: unite.cms.api_request_matcher
            stateless: true
            guard:
                authenticators:
                    - unite.cms.api_key_authenticator

        # Main firewall for authentication via user or remember_me cookie.
        main:
            anonymous: ~
            provider: unite_core_user
            form_login:
                login_path: unitecms_core_authentication_login
                check_path: unitecms_core_authentication_login
            logout:
                path:   unitecms_core_logout
                target: unitecms_core_authentication_login
            remember_me:
                secret:   '%env(APP_SECRET)%'
                lifetime: 8640000 # 100 days
                path:     /
                domain:   '%default_hostname%'
