twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: UniteCMS\CoreBundle\Controller\ExceptionController::showAction
    form_themes:
        - '@UniteCMSCore/Form/uikit_layout.html.twig'
        - '@UniteCMSCollectionField/Form/form_widgets.html.twig'
        - '@UniteCMSVariantsField/Form/form_widgets.html.twig'
    globals:
        unite: '@unite.cms.manager'
        site_name: '%site_name%'
