twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@UnitedCMSCore/Form/uikit_layout.html.twig'
        - '@UnitedCMSCollectionField/Form/form_widgets.html.twig'
        - '@UnitedCMSStorage/Form/form_widgets.html.twig'
    globals:
        united: '@united.cms.manager'
        site_name: '%site_name%'
        site_background: '%site_background%'
